#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.cloud.gateway: DEBUG
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:1025/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: bulletscreen1
        # /info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://client
        predicates:
        - Path=/client-bullet/info/**
      - id: bulletscreen2
        uri: lb:ws://client
        predicates:
        - Path=/client-bullet/**
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/incaseoffailureusethis
#        - RewritePath=/consumingserviceendpoint, /backingserviceendpoint
management:
  endpoints:
    web:
      exposure:
        include: refresh
